### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gcharest** [gcharest/gluko#3]
## Calculateur de glucides

- [ ] Refactorisation de la réactivité
- [ ] Couverture totale des tests (unit, integration, e2e)
- [ ] Amélioration de l'expérience utilisateur 
   - [ ] Initialiser avec un aliment vide plutôt qu'une liste vide (TBC) ou réinitialiser sans aliment
   - [ ] Ouverture de la boîte de dialogue lors de l'ajout d'un aliment (un clic de moins)
   - [ ] Saisi de chiffres en fonction de la langue choisi de l'interface plutôt que de la langue de l'appareil (FR-CA vs EN-CA a un impact sur la virgule ou le point pour les décimales)
   - [ ] Intégrer la recherche de facteurs directement dans 
- [ ] Profil utilisateurs (authentification)
- [ ] Historique des calculs
- [ ] Exportation des données (formats csv, json, etc.)

## Recherche de facteur glucidique

- [ ] Optimisation du chargement des données (à l'initialisation de l'app plutôt que de la page)
- [ ] Indicateur du chargement local des données
- [ ] Optimisation de la sauvegarde locale ([PWA](https://web.dev/learn/pwa/assets-and-data/))
- [ ] Ajout d'une option de rafraîchissement des données (PWA)
- [ ] Description de la source des données originale ([CNF](https://food-nutrition.canada.ca/cnf-fce/?lang=fre))
- [ ] Chargement de l'ensemble des données
- [ ] Ajout d'aliments favoris (dépend du profil utilisateur)
- [ ] Historique des recherches

## Design

- [ ] Choix des couleurs
- [ ] Design de l'interface
